language: node_js
install: npm install
script: 
  - npm run test
branchs:
  only:
  - master
script: 
  - ssh 
  - cd /var/wwwroot/nuxt-test
  - npm run build
  - pm2 delete nuxt-test
  - pm2 start ecosystem.config.js