language: node_js
node_js: stable
cache: npm
install: npm install
branchs:
  only:
  - master
addons:
  ssh_known_hosts:
  - 120.78.178.159
before_install:
- openssl aes-256-cbc -K $encrypted_b19672e7400e_key -iv $encrypted_b19672e7400e_iv
  -in id_rsa.enc -out ~/.ssh/id_rsa -d
after_success:
- chmod 600 ~/.ssh/id_rsa
- ssh root@120.78.178.159 -o StrictHostKeyChecking=no 'cd /var/wwwroot/nuxt-test && git fetch --all && git checkout master && git reset --hard && git pull origin master && npm install && npm run build && pm2 delete nuxt-test && pm2 start ecosystem.config.js'
